# Generated by Django 4.1.7 on 2023-07-08 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_orders_user_alter_orderupdate_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Product_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_Dimensions', models.CharField(max_length=40)),
                ('Date_First_Available', models.CharField(max_length=40)),
                ('ASIN', models.CharField(max_length=40)),
                ('Item_part_number', models.CharField(max_length=40)),
                ('Country_of_Origin', models.CharField(max_length=40)),
                ('Department', models.CharField(max_length=40)),
                ('Manufacturer', models.CharField(max_length=40)),
                ('Item_Weight', models.CharField(max_length=40)),
                ('Net_Quantity', models.CharField(max_length=40)),
                ('Generic_Name', models.CharField(max_length=40)),
                ('Best_Sellers_Rank', models.CharField(max_length=40)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
