# Generated by Django 4.1.7 on 2023-07-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_product_discription_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.CharField(max_length=500),
        ),
    ]
