# Generated by Django 4.1.7 on 2023-07-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_product_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.CharField(max_length=1000),
        ),
    ]
